name: breastcancer_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - scikit-learn
  - pandas
  - numpy
  - pip
  - pip:
      - mlflow
      - dagshub
      - joblib
      - python-dotenv
